version = 1

exclude_patterns = ["node_modules/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = ["nodejs"]